services:
  mongo:
    image: mongo:8
    # container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  test-api:
    build: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    # environment:
    #   SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mydb
    # command: >
    #   java -jar /app/test-api.jar
    #   --spring.data.mongodb.uri=mongodb://mongo:27017/mydb

# volumes:
#   mongodata:

#     environment:
#       SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mydb
#       # SPRING_DATA_MONGODB_URI: mongodb://${SPRING_DATA_MONGODB_HOST:mongo}:${SPRING_DATA_MONGODB_PORT:27017}/${SPRING_DATA_MONGODB_DATABASE:mydb}

#     command: >
#       java -jar /app/test-api.jar
#       --spring.data.mongodb.uri=mongodb://mongo:27017/mydb

volumes:
  mongodata:
